security:
    encoders:
        Design311\WebsiteBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: Design311\WebsiteBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: /
            provider: user_db
            form_login:
                use_referer: true
                login_path: /login/auth/
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout/
                target: /
            remember_me:
                key: V!UtONAWvl2gL-?ORKTm3gy32
                lifetime: 2592000
                path: /
                domain: ~
                always_remember_me: true
            security: true
            anonymous: true

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*/add/, roles: ROLE_USER }
        - { path: /recepten/.*/like/, roles: ROLE_USER }
        - { path: /recepten/.*/save/, roles: ROLE_USER }
        - { path: /recepten/.*/shop/, roles: ROLE_USER }
        - { path: /dinners/.*/accept/, roles: ROLE_USER }
        - { path: /dinners/.*/decline/, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }