design311website_homepage:
    path:      /
    defaults:  { _controller: Design311WebsiteBundle:Default:index }

design311website_login:
    pattern: /login/
    defaults: { _controller: Design311WebsiteBundle:User:login }

design311website_testing:
    pattern: /testing/
    defaults: { _controller: Design311WebsiteBundle:User:testing }

design311website_login_required:
    pattern: /login/{auth}/
    defaults: { _controller: Design311WebsiteBundle:User:login }

design311website_login_check:
    pattern: /login_check

design311website_logout:
    pattern: /logout/

design311website_register:
    path:      /registreren/
    defaults:  { _controller: Design311WebsiteBundle:User:register }

design311website_user_aantal_personen:
    path:     /recepten/aantal/
    defaults: { _controller: Design311WebsiteBundle:User:changeAantal }

design311website_dinners:
    path:     /dinners/
    defaults: { _controller: Design311WebsiteBundle:Dinner:index }

design311website_dinners_add:
    path:     /dinners/add/
    defaults: { _controller: Design311WebsiteBundle:Dinner:add }

design311website_dinners_filter:
    path:     /dinners/filter/
    defaults: { _controller: Design311WebsiteBundle:Ajax:filterDinners }

design311website_dinners_detail:
    path:     /dinners/{permalink}/
    defaults: { _controller: Design311WebsiteBundle:Dinner:detail }

design311website_dinners_participate:
    path:     /dinners/{permalink}/deelnemen/
    defaults: { _controller: Design311WebsiteBundle:Dinner:participate }

design311website_dinners_invite:
    path:     /dinners/{permalink}/uitnodigen/
    defaults: { _controller: Design311WebsiteBundle:Dinner:invite }

design311website_dinners_participant_decline:
    path:     /dinners/{permalink}/participant/{participantId}/decline/
    defaults: { _controller: Design311WebsiteBundle:Ajax:declineDinnerParticipant }

design311website_dinners_participant_accept:
    path:     /dinners/{permalink}/participant/{participantId}/accept/
    defaults: { _controller: Design311WebsiteBundle:Ajax:acceptDinnerParticipant }

design311website_dinners_invite_decline:
    path:     /dinners/{permalink}/invite/{inviteId}/decline/
    defaults: { _controller: Design311WebsiteBundle:Ajax:declineDinnerInvite }

design311website_dinners_invite_accept:
    path:     /dinners/{permalink}/invite/{inviteId}/accept/
    defaults: { _controller: Design311WebsiteBundle:Ajax:acceptDinnerInvite }

design311website_recepten:
    path:     /recepten/
    defaults: { _controller: Design311WebsiteBundle:Recipe:index }

design311website_recepten_add:
    path:     /recepten/add/
    defaults: { _controller: Design311WebsiteBundle:Recipe:add }

design311website_recepten_shoppinglist:
    path:     /recepten/shoppinglist/
    defaults: { _controller: Design311WebsiteBundle:Recipe:shoppinglist }

design311website_recepten_zoeken:
    path:     /recepten/zoeken/
    defaults: { _controller: Design311WebsiteBundle:Recipe:search }

design311website_recepten_category:
    path:     /recepten/{category}/
    defaults: { _controller: Design311WebsiteBundle:Recipe:category }

design311website_recepten_user:
    path:     /recepten/user/{username}/
    defaults: { _controller: Design311WebsiteBundle:Recipe:user }

design311website_recepten_like:
    path:     /recepten/{recipeId}/like/
    defaults: { _controller: Design311WebsiteBundle:Ajax:likeRecipe }

design311website_recepten_save:
    path:     /recepten/{recipeId}/save/
    defaults: { _controller: Design311WebsiteBundle:Ajax:saveRecipe }

design311website_recepten_shop:
    path:     /recepten/{recipeId}/shop/
    defaults: { _controller: Design311WebsiteBundle:Ajax:shopRecipe }

design311website_recepten_edit:
    path:     /recepten/{recipeId}/edit/
    defaults: { _controller: Design311WebsiteBundle:Recipe:edit }

design311website_recepten_detail:
    path:     /recepten/{category}/{permalink}/
    defaults: { _controller: Design311WebsiteBundle:Recipe:detail }