parameters:
#    acme_demo.example.class: Acme\DemoBundle\Example

services:
    design311.twig.twig_filters:
        class: Design311\WebsiteBundle\Twig\TwigFilters
        tags:
            - { name: twig.extension }
